export const copy = {
  quiz: {
    wrongAnswer: (correctAnswer: string) =>
      `Not quite — the right answer was ${correctAnswer}. Onwards!`,
    timeout: `Out of time on that one — let's keep going.`,
    streakReset: `Streak reset. Today's a fresh start 🔥`,
    correctAnswers: [
      'Nailed it!',
      "You're on fire!",
      'Big brain energy!',
      "That's the one!",
      'Galaxy brain move!',
      'Boom! Knowledge unlocked.',
      "Couldn't have said it better myself.",
      "Chef's kiss. Perfection.",
      'You make this look easy.',
      'Correctamundo!',
    ],
    wrongEncouragements: [
      'Almost!',
      'So close!',
      'Good try!',
      'Not quite, but we love the confidence!',
      'Hey, you learned something new!',
      "That was a tricky one — don't sweat it.",
      "Shake it off — you've got the next one.",
      "Nobody's perfect (except that one person on the leaderboard).",
    ],
    streakMessages: [
      { threshold: 3, message: "3 in a row! You're on a roll!" },
      { threshold: 5, message: "5 streak! You're unstoppable!" },
      { threshold: 7, message: '7 in a row! Are you cheating? Just kidding.' },
      { threshold: 10, message: '10 streak! LEGENDARY STATUS!' },
    ],
    milestones: {
      halfway: "Halfway there! You're doing great.",
      almostDone: 'Almost done — finish strong!',
      lastQuestion: 'Last question — make it count!',
      oneMore: 'Just one more. You got this.',
    },
  },
  loading: [
    'Warming up the neurons…',
    'Loading brain teasers…',
    'Preparing your challenge…',
    'Shuffling the questions…',
    'Consulting the trivia gods…',
    'Polishing the trophies…',
  ],
  results: {
    headlines: [
      {
        min: 100,
        max: 100,
        emoji: '🏆',
        title: 'FLAWLESS VICTORY!',
        subtitle: "You didn't miss a single one. Legend status unlocked.",
      },
      {
        min: 90,
        max: 99,
        emoji: '🌟',
        title: 'So close to perfection!',
        subtitle: "You're a quiz prodigy in the making.",
      },
      {
        min: 80,
        max: 89,
        emoji: '⭐',
        title: 'Impressive brain power!',
        subtitle: 'You really know your stuff.',
      },
      {
        min: 70,
        max: 79,
        emoji: '🎯',
        title: 'Solid effort!',
        subtitle: "You're above average — keep that momentum going.",
      },
      {
        min: 60,
        max: 69,
        emoji: '💪',
        title: 'Not bad at all!',
        subtitle: "A little more practice and you'll be unstoppable.",
      },
      {
        min: 50,
        max: 59,
        emoji: '📈',
        title: "You're getting there!",
        subtitle: 'Every quiz makes you sharper.',
      },
      {
        min: 0,
        max: 49,
        emoji: '📚',
        title: 'Every expert was once a beginner.',
        subtitle: 'Try again and watch your score climb!',
      },
    ],
  },
  emptyStates: {
    leaderboard: `No one's claimed this corner yet — be the first.`,
    noBadges: 'No badges yet — your first unlock is one great run away.',
    noPublishedQuizzes: 'No published quizzes yet — hit publish and show the world what you made.',
    noSessions: 'No sessions yet — your next quiz run could be your breakout moment.',
    noCategoryResults: 'No quizzes match this search yet — try another filter and keep exploring.',
    noQuestions: 'This quiz has no questions yet. Someone got lazy! 🙃',
  },
  play: {
    quitTitle: 'Leave already? 🥺',
    quitDescription:
      'Your quiz streak is looking pretty good right now... Are you sure you want to bail?',
    quitConfirm: "Fine, I'll go",
    quitCancel: 'Nah, keep playing',
    typeHints: {
      SINGLE: 'Pick one (no pressure)',
      TRUEFALSE: 'True or false? Trust your gut!',
      FILL_BLANK: 'Type your answer — spelling counts (kinda)',
    },
    progressEncouragements: [
      "You're crushing it!",
      'Keep that momentum!',
      'Look at you go!',
      'On a roll today!',
      'Brain cells activated!',
    ],
  },
  hero: {
    duelTitle: 'Duel Mode',
    duelDescription:
      "Think you're smart? Prove it in real-time 1v1 combat. Challenge a friend, share a code, and let the best brain win.",
    duelCta: 'Start a Duel',
    duelCtaGuest: 'Sign Up to Duel',
    dailyTitle: 'Daily Challenge',
    dailyDescription:
      'A fresh brain-buster every 24 hours. Keep your streak alive, earn bonus XP, and bragging rights included.',
    dailyCta: 'Play Challenge',
    dailyCtaGuest: 'Sign Up to Play',
  },
  auth: {
    signInTagline: 'Welcome back, quiz champion! Your streak misses you.',
    signInSocialProof: 'Join 50,000+ quiz enthusiasts',
    signUpTagline: 'Start your quiz journey. Thousands of brain teasers await.',
    signUpBenefits: [
      'Save your progress and XP',
      'Earn badges and climb levels',
      'Compete on global leaderboards',
      'Challenge friends in real-time duels',
    ],
  },
  duel: {
    howItWorks: [
      { step: '1', title: 'Create', description: 'Pick a category and set your rules' },
      { step: '2', title: 'Share', description: 'Send the code to your opponent' },
      { step: '3', title: 'Battle', description: 'Answer fast — every second counts' },
      { step: '4', title: 'Win', description: 'Highest score takes the glory' },
    ],
    tagline: 'Think faster than your opponent. Every second counts. Glory awaits.',
  },
}
