export interface MapRegion {
  id: string
  name: string
  svgPath: string
  countries: CountryInfo[]
}

export interface CountryInfo {
  id: string
  name: string
}

export const MAP_REGIONS: MapRegion[] = [
  {
    id: 'europe',
    name: 'Europe',
    svgPath: '/maps/europe.svg',
    countries: [
      { id: 'iceland', name: 'Iceland' },
      { id: 'norway', name: 'Norway' },
      { id: 'sweden', name: 'Sweden' },
      { id: 'finland', name: 'Finland' },
      { id: 'united-kingdom', name: 'United Kingdom' },
      { id: 'ireland', name: 'Ireland' },
      { id: 'france', name: 'France' },
      { id: 'spain', name: 'Spain' },
      { id: 'portugal', name: 'Portugal' },
      { id: 'germany', name: 'Germany' },
      { id: 'poland', name: 'Poland' },
      { id: 'italy', name: 'Italy' },
      { id: 'netherlands', name: 'Netherlands' },
      { id: 'belgium', name: 'Belgium' },
      { id: 'switzerland', name: 'Switzerland' },
      { id: 'austria', name: 'Austria' },
      { id: 'czechia', name: 'Czechia' },
      { id: 'romania', name: 'Romania' },
      { id: 'hungary', name: 'Hungary' },
      { id: 'greece', name: 'Greece' },
      { id: 'turkey', name: 'Turkey' },
      { id: 'ukraine', name: 'Ukraine' },
      { id: 'belarus', name: 'Belarus' },
      { id: 'russia', name: 'Russia' },
      { id: 'denmark', name: 'Denmark' },
      { id: 'estonia', name: 'Estonia' },
      { id: 'latvia', name: 'Latvia' },
      { id: 'lithuania', name: 'Lithuania' },
      { id: 'serbia', name: 'Serbia' },
      { id: 'croatia', name: 'Croatia' },
      { id: 'bulgaria', name: 'Bulgaria' },
    ],
  },
  {
    id: 'africa',
    name: 'Africa',
    svgPath: '/maps/africa.svg',
    countries: [
      { id: 'morocco', name: 'Morocco' },
      { id: 'algeria', name: 'Algeria' },
      { id: 'tunisia', name: 'Tunisia' },
      { id: 'libya', name: 'Libya' },
      { id: 'egypt', name: 'Egypt' },
      { id: 'mauritania', name: 'Mauritania' },
      { id: 'mali', name: 'Mali' },
      { id: 'niger', name: 'Niger' },
      { id: 'chad', name: 'Chad' },
      { id: 'sudan', name: 'Sudan' },
      { id: 'senegal', name: 'Senegal' },
      { id: 'guinea', name: 'Guinea' },
      { id: 'sierra-leone', name: 'Sierra Leone' },
      { id: 'ivory-coast', name: 'Ivory Coast' },
      { id: 'ghana', name: 'Ghana' },
      { id: 'nigeria', name: 'Nigeria' },
      { id: 'cameroon', name: 'Cameroon' },
      { id: 'ethiopia', name: 'Ethiopia' },
      { id: 'somalia', name: 'Somalia' },
      { id: 'kenya', name: 'Kenya' },
      { id: 'tanzania', name: 'Tanzania' },
      { id: 'dr-congo', name: 'DR Congo' },
      { id: 'angola', name: 'Angola' },
      { id: 'mozambique', name: 'Mozambique' },
      { id: 'madagascar', name: 'Madagascar' },
      { id: 'south-africa', name: 'South Africa' },
      { id: 'namibia', name: 'Namibia' },
      { id: 'botswana', name: 'Botswana' },
      { id: 'zimbabwe', name: 'Zimbabwe' },
    ],
  },
  {
    id: 'americas',
    name: 'Americas',
    svgPath: '/maps/americas.svg',
    countries: [
      { id: 'canada', name: 'Canada' },
      { id: 'united-states', name: 'United States' },
      { id: 'mexico', name: 'Mexico' },
      { id: 'guatemala', name: 'Guatemala' },
      { id: 'honduras', name: 'Honduras' },
      { id: 'nicaragua', name: 'Nicaragua' },
      { id: 'costa-rica', name: 'Costa Rica' },
      { id: 'panama', name: 'Panama' },
      { id: 'colombia', name: 'Colombia' },
      { id: 'venezuela', name: 'Venezuela' },
      { id: 'guyana', name: 'Guyana' },
      { id: 'suriname', name: 'Suriname' },
      { id: 'ecuador', name: 'Ecuador' },
      { id: 'peru', name: 'Peru' },
      { id: 'brazil', name: 'Brazil' },
      { id: 'bolivia', name: 'Bolivia' },
      { id: 'chile', name: 'Chile' },
      { id: 'argentina', name: 'Argentina' },
      { id: 'paraguay', name: 'Paraguay' },
      { id: 'uruguay', name: 'Uruguay' },
    ],
  },
  {
    id: 'asia',
    name: 'Asia',
    svgPath: '/maps/asia.svg',
    countries: [
      { id: 'russia', name: 'Russia' },
      { id: 'china', name: 'China' },
      { id: 'india', name: 'India' },
      { id: 'japan', name: 'Japan' },
      { id: 'south-korea', name: 'South Korea' },
      { id: 'north-korea', name: 'North Korea' },
      { id: 'mongolia', name: 'Mongolia' },
      { id: 'kazakhstan', name: 'Kazakhstan' },
      { id: 'uzbekistan', name: 'Uzbekistan' },
      { id: 'iran', name: 'Iran' },
      { id: 'iraq', name: 'Iraq' },
      { id: 'saudi-arabia', name: 'Saudi Arabia' },
      { id: 'turkey', name: 'Turkey' },
      { id: 'pakistan', name: 'Pakistan' },
      { id: 'afghanistan', name: 'Afghanistan' },
      { id: 'thailand', name: 'Thailand' },
      { id: 'vietnam', name: 'Vietnam' },
      { id: 'myanmar', name: 'Myanmar' },
      { id: 'indonesia', name: 'Indonesia' },
      { id: 'philippines', name: 'Philippines' },
      { id: 'malaysia', name: 'Malaysia' },
      { id: 'taiwan', name: 'Taiwan' },
      { id: 'bangladesh', name: 'Bangladesh' },
      { id: 'nepal', name: 'Nepal' },
      { id: 'sri-lanka', name: 'Sri Lanka' },
      { id: 'israel', name: 'Israel' },
      { id: 'jordan', name: 'Jordan' },
      { id: 'syria', name: 'Syria' },
    ],
  },
  {
    id: 'oceania',
    name: 'Oceania',
    svgPath: '/maps/oceania.svg',
    countries: [
      { id: 'australia', name: 'Australia' },
      { id: 'new-zealand', name: 'New Zealand' },
      { id: 'papua-new-guinea', name: 'Papua New Guinea' },
      { id: 'indonesia-east', name: 'Indonesia (East)' },
      { id: 'fiji', name: 'Fiji' },
      { id: 'solomon-islands', name: 'Solomon Islands' },
      { id: 'new-caledonia', name: 'New Caledonia' },
      { id: 'tonga', name: 'Tonga' },
      { id: 'samoa', name: 'Samoa' },
    ],
  },
]

export function getRegionById(id: string): MapRegion | undefined {
  return MAP_REGIONS.find((r) => r.id === id)
}

export function getCountryName(regionId: string, countryId: string): string | undefined {
  const region = getRegionById(regionId)
  return region?.countries.find((c) => c.id === countryId)?.name
}
