-- Add new question types
ALTER TYPE "QuestionType" ADD VALUE IF NOT EXISTS 'ORDER';
ALTER TYPE "QuestionType" ADD VALUE IF NOT EXISTS 'MATCH';
ALTER TYPE "QuestionType" ADD VALUE IF NOT EXISTS 'NUMBER_GUESS';
ALTER TYPE "QuestionType" ADD VALUE IF NOT EXISTS 'GROUPS';

-- Add new quiz formats
ALTER TYPE "QuizFormat" ADD VALUE IF NOT EXISTS 'ORDER';
ALTER TYPE "QuizFormat" ADD VALUE IF NOT EXISTS 'MATCH';
ALTER TYPE "QuizFormat" ADD VALUE IF NOT EXISTS 'ODD_ONE_OUT';
ALTER TYPE "QuizFormat" ADD VALUE IF NOT EXISTS 'TYPE_ANSWER';
ALTER TYPE "QuizFormat" ADD VALUE IF NOT EXISTS 'NUMBER_GUESS';
ALTER TYPE "QuizFormat" ADD VALUE IF NOT EXISTS 'IMAGE_REVEAL';
ALTER TYPE "QuizFormat" ADD VALUE IF NOT EXISTS 'AUDIO_CHOICE';
ALTER TYPE "QuizFormat" ADD VALUE IF NOT EXISTS 'VERSUS';
ALTER TYPE "QuizFormat" ADD VALUE IF NOT EXISTS 'CONNECTIONS';
ALTER TYPE "QuizFormat" ADD VALUE IF NOT EXISTS 'ANAGRAM';
ALTER TYPE "QuizFormat" ADD VALUE IF NOT EXISTS 'MEMORY_FLASH';
